currency_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("exchange_rates.urls")),
    path("admin/", admin.site.urls),
]

exchange_rates/urls.py
from django.urls import path
from . import views

app_name = 'exchange_rates'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:base_currency>/<str:target_currency>/<str:value>', views.ExchangeRateView.as_view(),
         name='exchange_rate'),
    path('<str:base_currency>/<str:target_currency>/<str:value>/calc', views.calc_exchange, name='calc_exchange'),
    path('latest_rate/<str:base_currency>/<str:target_currency>/', views.LatestRateView.as_view(), name='latest_rate'),
    path('<str:base_currency>/<str:target_currency>/historical_data/<str:start_date>/<str:end_date>',
         views.HistoricalDataView.as_view(),
         name='historical_data'),
    path('<str:base_currency>/<str:target_currency>/historical_data/setup', views.set_history, name='change_range'),
    path('historical_data/<str:base_currency>/<str:target_currency>/<str:start_date>/<str:end_date>',
         views.HistoricalDataJSView.as_view(), name='historical_data_js'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:base_currency>/<str:target_currency>/latest_rate/', views.LatestRateView.as_view(), name='latest_rate'),
    path('<str:base_currency>/<str:target_currency>/historical_data/', views.HistoricalDataView.as_view(),
         name='historical_data'),
]

exchange_rates/models.py
import uuid
from django.db import models


class Checker(models.Model):
    """
    The main model class to represent a currency exchange on database.

    ...
    Attributes
    ------------
    id : A unique identifier auto generated.
    base_currency : The base currency of the exchange.
    target_currency : The target currency of the exchange.
    check_period : The time between checks.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    base_currency = models.CharField(max_length=3)
    target_currency = models.CharField(max_length=3)
    check_period = models.DurationField('check period')

    def __str__(self):
        return f'{self.base_currency}$ -> {self.target_currency}$: Checks every {self.check_period}'


class Rate(models.Model):
    """
    The main model class to represent a currency exchange on database.

    ...
    Attributes
    ------------
    id : A unique identifier auto generated.
    base_currency : The base currency of the exchange.
    target_currency : The target currency of the exchange.
    rate : The exchange rate.
    timestamp : The exact date and time that the exchange rate was checked.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    base_currency = models.CharField(max_length=3)
    target_currency = models.CharField(max_length=3)
    rate = models.FloatField()
    timestamp = models.DateTimeField('date checked')

    def __str__(self):
        return f'({self.timestamp}) {self.base_currency}$ 1 -> {self.target_currency}$ {self.rate}'

exchange_rates/views.py
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Rate


class IndexView(generic.ListView):
    """
    The Homepage view.
    """
    template_name = 'exchange_rates/index.html'
    context_object_name = 'latest_rates'

    def get_queryset(self):
        latest_rates = Rate.objects.order_by('-timestamp')
        exchanges = {}
        for rate in latest_rates:
            key = f'{rate.base_currency}->{rate.target_currency}'
            if key not in exchanges:
                exchanges[key] = rate.id
            else:
                latest_rates = latest_rates.exclude(id=rate.id)
        return latest_rates


class ExchangeRateView(generic.ListView):
    """
    The Exchange Rates view.
    Which you can calculate the value of a Currency amount based on the latest rate.
    """
    model = Rate
    template_name = 'exchange_rates/exchange_rate.html'
    context_object_name = 'info'

    def get_queryset(self):
        rates = Rate.objects.filter(
            base_currency=self.kwargs['base_currency'],
            target_currency=self.kwargs['target_currency'],
        ).order_by('-timestamp')
        if len(rates) < 1:
            return {
                'latest_rate': None,
                'latest_rates': [],
                'value': None,
                'result': None,
            }
        latest_rates = Rate.objects.order_by('-timestamp')
        exchanges = {}
        for rate in latest_rates:
            key = f'{rate.base_currency}->{rate.target_currency}'
            if key not in exchanges:
                exchanges[key] = rate.id
            else:
                latest_rates = latest_rates.exclude(id=rate.id)
        return {
            'latest_rate': rates[0],
            'latest_rates': latest_rates,
            'value': float(self.kwargs['value']),
            'result': rates[0].rate * float(self.kwargs['value']),
        }


def calc_exchange(request, base_currency, target_currency, value):
    """
    The Calculate Exchange view.
    That redirects you to the calculated rate.
    This view is executed by the Exchange Rates view form.
    """
    if request.method == 'POST':
        value = float(request.POST['BRL'].replace('$', '').replace(',', '.'))
        return HttpResponseRedirect(
            reverse(
                'exchange_rates:exchange_rate',
                args=(
                    base_currency,
                    target_currency,
                    value,
                ),
            )
        )


class LatestRateView(generic.ListView):
    """
    The Latest Rate view.
    Which you can retrieve a json-like information about a currency exchange.
    """
    model = Rate
    template_name = 'exchange_rates/latest_rate.html'
    context_object_name = 'rate'

    def get_queryset(self):
        try:
            rates = Rate.objects.filter(
                base_currency=self.kwargs['base_currency'],
                target_currency=self.kwargs['target_currency'],
            )
            if len(rates) < 1:
                raise Rate.DoesNotExist
        except Rate.DoesNotExist:
            raise Http404
        timestamp = rates[0].timestamp
        latest_rate = rates[0]
        for rate in rates:
            if rate.timestamp > timestamp:
                latest_rate = rate
                timestamp = rate.timestamp
        rate_js = {
            'base_currency': latest_rate.base_currency,
            'target_currency': latest_rate.target_currency,
            'rate': latest_rate.rate,
            'timestamp': latest_rate.timestamp,
        }
        return rate_js


def convert_tz(date_str):
    """
    Simple general static str to timezone method
    """
    return timezone.make_aware(timezone.datetime.strptime(date_str, '%Y-%m-%d'))


class HistoricalDataView(generic.ListView):
    """
    The Historical Data view.
    Which you can see the historical information about a currency exchange.
    """
    template_name = 'exchange_rates/historical_data.html'
    context_object_name = 'info'

    def get_queryset(self):
        start_date = self.kwargs['start_date']
        end_date = self.kwargs['end_date']
        rates = Rate.objects.filter(
            base_currency=self.kwargs['base_currency'],
            target_currency=self.kwargs['target_currency'],
        ).order_by('timestamp')
        if start_date == '0':
            if len(rates) > 0:
                start_date = rates[0].timestamp
            else:
                start_date = timezone.now()
        else:
            start_date = convert_tz(start_date)
        if end_date == '0':
            if len(rates) > 0:
                end_date = rates[len(rates)-1].timestamp
            else:
                end_date = timezone.now()
        else:
            end_date = convert_tz(end_date)
        if start_date > end_date:
            aux = start_date
            start_date = end_date
            end_date = aux

        rates = Rate.objects.filter(
            base_currency=self.kwargs['base_currency'],
            target_currency=self.kwargs['target_currency'],
            timestamp__gte=start_date,
            timestamp__lte=end_date,
        ).order_by('-timestamp')
        latest_rates = Rate.objects.order_by('-timestamp')
        exchanges = {}
        for rate in latest_rates:
            key = f'{rate.base_currency}->{rate.target_currency}'
            if key not in exchanges:
                exchanges[key] = rate.id
            else:
                latest_rates = latest_rates.exclude(id=rate.id)
        return {'base': self.kwargs['base_currency'], 'target': self.kwargs['target_currency'], 'history': rates,
                'latest_rates': latest_rates}


def set_history(request, base_currency, target_currency):
    """
    The Set History view.
    That redirects you to the filtered history list.
    This view is executed by the History Data view form.
    """
    if request.method == 'POST':
        start = request.POST['start']
        end = request.POST['end']
        if not start or start == '':
            start = '0'
        if not end or end == '':
            end = '0'
        return HttpResponseRedirect(
            reverse(
                'exchange_rates:historical_data',
                args=(
                    base_currency,
                    target_currency,
                    start,
                    end,
                ),
            )
        )


class HistoricalDataJSView(generic.ListView):
    """
    The Historical Data JS view.
    Which you can retrieve a json-like information about a currency exchange history.
    """
    model = Rate
    template_name = 'exchange_rates/historical_data_js.html'
    context_object_name = 'history'

    def get_queryset(self):
        start_date = self.kwargs['start_date']
        end_date = self.kwargs['end_date']
        rates = Rate.objects.filter(
            base_currency=self.kwargs['base_currency'],
            target_currency=self.kwargs['target_currency'],
        ).order_by('timestamp')
        if start_date == '0':
            if len(rates) > 0:
                start_date = rates[0].timestamp
            else:
                start_date = timezone.now()
        else:
            start_date = convert_tz(start_date)
        if end_date == '0':
            if len(rates) > 0:
                end_date = rates[len(rates)-1].timestamp
            else:
                end_date = timezone.now()
        else:
            end_date = convert_tz(end_date)
        if start_date > end_date:
            aux = start_date
            start_date = end_date
            end_date = aux

        rates = Rate.objects.filter(
            base_currency=self.kwargs['base_currency'],
            target_currency=self.kwargs['target_currency'],
            timestamp__gte=start_date,
            timestamp__lte=end_date,
        ).order_by('-timestamp')
        rates_js = []
        for rate in rates:
            rates_js.append({
                'base_currency': rate.base_currency,
                'target_currency': rate.target_currency,
                'rate': rate.rate,
                'timestamp': rate.timestamp,
            })
        return rates_js

exchange_rates/templates/exchange_rates/exchange_rate.html
<!DOCTYPE html>
<html lang="pt">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Montaga&display=swap" rel="stylesheet"/>
    <link href="{% static 'exchange_rates/style/index.css' %}" rel="stylesheet"/>
    <title>{{ info.latest_rate.base_currency }} -> {{ info.latest_rate.target_currency }}</title>
</head>
<body>
<div class="DesktopHome">
    <div class="MainFrame">
        <img class="BackgroundImage" src="{% static 'exchange_rates/resources/background_image.jpg' %}"/>
        <div class="CurrencyExchangeChecker">Currency Exchange Checkers</div>
        <div class="ExchangesListFrame">
            {% if info.latest_rates %}
            {% for rate in info.latest_rates %}
            <a class="ExchangeButton"
               href="{% url 'exchange_rates:exchange_rate' rate.base_currency rate.target_currency 1.0 %}">
                {{ rate.base_currency }} => {{ rate.target_currency }}
            </a>
            {% endfor %}
            {% else %}
            <div class="LatestExchangeUpdate">
                No exchanges checked yet.
            </div>
            {% endif %}
        </div>
        <div class="LatestExchangeFrame">
            {% if info.latest_rates %}
            <div class="LatestExchangeTable">
                <div class="LatestExchangeDiv">
                    <label class="CurrencyDiv">
                        {{ info.latest_rate.base_currency }}
                    </label>
                    <form class="CurrencyDiv"
                          action="{% url 'exchange_rates:calc_exchange' info.latest_rate.base_currency info.latest_rate.target_currency info.value %}"
                          method="post">
                        {% csrf_token %}
                        <input type="text" name="{{ info.latest_rate.base_currency }}"
                               value="${{ info.value|floatformat:2 }}">
                    </form>
                </div>
                <div class="LatestExchangeDiv">
                    <label class="CurrencyDiv">
                        {{ info.latest_rate.target_currency }}
                    </label>
                    <div class="CurrencyDiv">
                        $ {{ info.result|floatformat:2 }}
                    </div>
                </div>
            </div>
            {% else %}
            <div class="LatestExchangeUpdate">
                No exchanges checked yet.
            </div>
            {% endif %}
            <div class="MenuDiv">
                <a class="MenuButton" href="{% url 'exchange_rates:index'%}">Home</a>
                {% if info.latest_rates %}
                <a class="MenuButton"
                   href="{% url 'exchange_rates:historical_data' info.latest_rate.base_currency info.latest_rate.target_currency 0 0%}">Check
                    history</a>
                {% endif %}
            </div>
            {% if info.latest_rates %}
            <div class="LatestExchangeUpdate">
                Última atualização: {{ info.latest_rate.timestamp }}
            </div>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

exchange_rates/templates/exchange_rates/historical_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>History: {{ rates.0.base_currency }} -> {{ rates.0.target_currency }}</title>
</head>
<body>
<div>
    <ul>
        {% for rate in rates %}
        <li>
            <p>
                {{ rate.timestamp }}: {{ rate.rate|floatformat:2 }}
            </p>
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    <a href="{% url 'exchange_rates:index'%}">Home</a>
    <a href="{% url 'exchange_rates:latest_rate' rates.0.base_currency rates.0.target_currency%}">Check
        latest</a>
</div>
</body>
</html>

exchange_rates/templates/exchange_rates/historical_data_js.html
{{ history }}

exchange_rates/templates/exchange_rates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Montaga&display=swap" rel="stylesheet" />
    <link href="{% static 'exchange_rates/style/index.css' %}" rel="stylesheet" />
    <title>Exchanges</title>
</head>
<body>
<div class="DesktopHome">
  <div class="MainFrame">
    <img class="BackgroundImage" src="{% static 'exchange_rates/resources/background_image.jpg' %}" />
    <div class="CurrencyExchangeChecker">Currency Exchange Checkers</div>
    <div class="ExchangesListFrame">
        {% if latest_rates %}
        {% for rate in latest_rates %}
        <a class="ExchangeButton" href="{% url 'exchange_rates:exchange_rate' rate.base_currency rate.target_currency 1%}">
            {{ rate.base_currency }} => {{ rate.target_currency }}
        </a>
        {% endfor %}
        {% else %}
        <div class="LatestExchangeUpdate">
            No exchanges checked yet.
        </div>
        {% endif %}
    </div>
  </div>
</div>
</body>
</html>

exchange_rates/templates/exchange_rates/latest_rate.html
{{ rate }}