currency_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("exchange_rates.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:base_currency>/<str:target_currency>/latest_rate/', views.LatestRateView.as_view(), name='latest_rate'),
    path('<str:base_currency>/<str:target_currency>/historical_data/', views.HistoricalDataView.as_view(),
         name='historical_data'),
]

polls/views.py
from django.db.models import F
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from .models import Rate


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_rates'

    def get_queryset(self):
        latest_rates = Rate.objects.order_by('-timestamp')
        exchanges = {}
        for rate in latest_rates:
            key = f'{rate.base_currency}->{rate.target_currency}'
            if key not in exchanges:
                exchanges[key] = rate.id
            else:
                latest_rates = latest_rates.exclude(id=rate.id)
        return latest_rates


class LatestRateView(generic.ListView):
    model = Rate
    template_name = 'polls/latest_exchange.html'
    context_object_name = 'latest_rate'

    def get_queryset(self):
        rates = Rate.objects.filter(base_currency=self.kwargs['base_currency'],
                                    target_currency=self.kwargs['target_currency'])
        if len(rates) < 1:
            raise Rate.DoesNotExist
        timestamp = rates[0].timestamp
        latest_rate = rates[0]
        for rate in rates:
            if rate.timestamp > timestamp:
                latest_rate = rate
                timestamp = rate.timestamp
        return latest_rate


class HistoricalDataView(generic.ListView):
    template_name = 'polls/historical_data.html'
    context_object_name = 'rates'

    def get_queryset(self):
        rates = Rate.objects.filter(base_currency=self.kwargs['base_currency'],
                                    target_currency=self.kwargs['target_currency'])
        if len(rates) < 1:
            raise Rate.DoesNotExist

        return rates.order_by('-timestamp')

polls/templates/polls/historical_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>History: {{ rates.0.base_currency }} -> {{ rates.0.target_currency }}</title>
</head>
<body>
<div>
    <ul>
        {% for rate in rates %}
        <li>
            <p>
                {{ rate.timestamp }}: {{ rate.rate|floatformat:2 }}
            </p>
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    <a href="{% url 'polls:index'%}">Home</a>
    <a href="{% url 'polls:latest_rate' rates.0.base_currency rates.0.target_currency%}">Check
        history</a>
</div>
</body>
</html>

polls/templates/polls/latest_exchange.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ latest_rate.base_currency }} -> {{ latest_rate.target_currency }}</title>
</head>
<body>
<div>
    {{ latest_rate.base_currency }}$ 1.00 -> {{ latest_rate.target_currency }}$ {{ latest_rate.rate|floatformat:2 }};
    Last update: {{ latest_rate.timestamp }}
</div>
<div>
    <a href="{% url 'polls:index'%}">Home</a>
    <a href="{% url 'polls:historical_data' latest_rate.base_currency latest_rate.target_currency%}">Check
        history</a>
</div>
</body>
</html>